apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-hello-michael
  labels:
    app: udacity-capstone-hello-michael
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"    
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: udacity-capstone-hello-michael