apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-hello-michael
  labels:
    app: udacity-capstone-hello-michael
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: udacity-capstone-hello-michael