version: 2.1

orbs:
  docker: circleci/docker@2.1.4
  aws-cli: circleci/aws-cli@3.1
  aws-eks: circleci/aws-eks@2.2
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  build-and-push-docker-image:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKERHUB_LOGIN
          docker-password: DOCKERHUB_PASSWORD
      - docker/build:
          image: mivodu/udacity-capstone-hello-michael
          tag: latest
      - docker/push:
          image: mivodu/udacity-capstone-hello-michael
          tag: latest
  lint-cfn:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Validate CloudFormation template
          command: pip install cfn-lint && cfn-lint cfn-eks-template.yml            
  deploy-cfn:
    parameters:
      stack-name:
        description: Name of the CloudFormation stack
        type: string
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Create cloudformation stack if it doesn't exist yet
          command: |
            if aws cloudformation list-stacks --stack-status-filter CREATE_COMPLETE | grep -F '"StackName": "Udacity-Capstone-Hello-Michael"'
            then
              echo "Cloudformation stack already exists, nothing to create"
            else
              echo "Cloudformation stack does not exist yet, we have to create it"
              aws cloudformation deploy \
                --template cfn-eks-template.yml \
                --stack << parameters.stack-name >> \              
            fi
          no_output_timeout: 30m
  create-deployment:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: "udacity-capstone-eks-cluster"
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: app-deployment.yaml
          get-rollout-status: true
          resource-name: deployment/hello-michael
      - kubernetes/create-or-update-resource:
          resource-file-path: app-service.yaml

workflows:
  default:
    jobs:
      - docker/hadolint
      - build-and-push-docker-image:
          requires: 
            - docker/hadolint
      - lint-cfn
      - deploy-cfn:
          stack-name: Udacity-Capstone-Hello-Michael
          requires:
            - lint-cfn
      - create-deployment:
          requires:
            - build-and-push-docker-image
            - deploy-cfn
